# Proyecto 1 - Parte 1

In [ ]:
import pandas as pd

-https://www.football-data.co.uk/data.php

In [109]:
#Leer  1 archivo csv de un sitioweb

df_premier2024= pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

#Mostrar dataframe 

df_premier2024

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,E0,20/04/2025,14:00,Fulham,Chelsea,1,2,A,1,0,...,1.93,2.00,1.92,2.01,1.93,2.02,1.88,1.94,1.94,2.05
326,E0,20/04/2025,14:00,Ipswich,Arsenal,0,4,A,0,2,...,1.86,2.07,1.86,2.07,1.90,2.07,1.85,2.00,1.90,2.07
327,E0,20/04/2025,14:00,Man United,Wolves,0,1,A,0,0,...,1.89,2.04,1.88,2.04,1.89,2.08,1.86,2.02,1.93,2.06
328,E0,20/04/2025,16:30,Leicester,Liverpool,0,1,A,0,0,...,1.78,2.03,1.83,2.08,1.88,2.12,1.83,2.03,1.87,2.14
329,E0,21/04/2025,20:00,Tottenham,Nott'm Forest,1,2,A,0,2,...,2.01,1.80,2.08,1.85,2.09,1.86,2.05,1.81,2.10,1.89

In [111]:
#Cambiar nombre de columnas
df_premier2024.rename(columns={'Date':'date',
                               'HomeTeam':'home_team',
                               'AwayTeam':'away_team',
                               'FTHG':'home_goals',
                               'FTAG':'away_goals',},inplace = True)

#Mpostrar dataframe
df_premier2024

,Div,date,Time,home_team,away_team,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,E0,20/04/2025,14:00,Fulham,Chelsea,1,2,A,1,0,...,1.93,2.00,1.92,2.01,1.93,2.02,1.88,1.94,1.94,2.05
326,E0,20/04/2025,14:00,Ipswich,Arsenal,0,4,A,0,2,...,1.86,2.07,1.86,2.07,1.90,2.07,1.85,2.00,1.90,2.07
327,E0,20/04/2025,14:00,Man United,Wolves,0,1,A,0,0,...,1.89,2.04,1.88,2.04,1.89,2.08,1.86,2.02,1.93,2.06
328,E0,20/04/2025,16:30,Leicester,Liverpool,0,1,A,0,0,...,1.78,2.03,1.83,2.08,1.88,2.12,1.83,2.03,1.87,2.14
329,E0,21/04/2025,20:00,Tottenham,Nott'm Forest,1,2,A,0,2,...,2.01,1.80,2.08,1.85,2.09,1.86,2.05,1.81,2.10,1.89

# proyecto 1 Segunda parte

#### Leer .csv de Multiples URLs con Pandas

#Estructura de un link
- https://www.football-data.co.uk/mmz4281/2425/E0.csv
- https://www.football-data.co.uk/mmz4281/2425/E1.csv

LINK: ROOT + SEASON + LEAGUE

In [32]:
# Estructura
"https://www.football-data.co.uk/mmz4281/" + "2425" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2425/E0.csv'

In [81]:
#Crear una variable root
root = "https://www.football-data.co.uk/mmz4281/"

In [60]:
#Multiples ligas
-https://www.football-data.co.uk/mmz4281/2425/E0.csv
-https://www.football-data.co.uk/mmz4281/2425/E1.csv
-https://www.football-data.co.uk/mmz4281/2425/E2.csv
-https://www.football-data.co.uk/mmz4281/2425/E3.csv
-https://www.football-data.co.uk/mmz4281/2425/EC.csv

SyntaxError: invalid syntax (4148875732.py, line 2)

In [66]:
#Crear lista de ligas

import pandas as pd

leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []

# hacer loop en la lista leagues, leer multiples csv y adjuntarlos
for league in leagues:
    df= pd.read_csv(root + '2425' + '/' + league + '.csv')
    frames.append(df)

In [70]:
#Tamaño de los frames
len(frames)

5

In [76]:
# mostrar 1er, 2do, y 3er elemento
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,10/08/2024,15:00,Aldershot,Forest Green,3,3,D,2,1,...,1.83,1.98,1.87,1.99,1.87,2.00,1.83,1.99,1.88,2.02
1,EC,10/08/2024,15:00,Altrincham,Woking,1,0,H,1,0,...,1.83,1.98,1.83,2.04,1.85,2.04,1.82,1.95,1.86,2.14
2,EC,10/08/2024,15:00,Boston Utd,Rochdale,0,3,A,0,2,...,1.85,1.95,1.88,1.98,1.88,1.98,1.84,1.93,1.92,2.00
3,EC,10/08/2024,15:00,Dag and Red,Wealdstone,2,1,H,0,0,...,1.90,1.90,1.89,1.95,1.91,1.95,1.87,1.88,1.91,2.06
4,EC,10/08/2024,15:00,Fylde,Solihull,3,2,H,1,2,...,1.78,2.03,1.76,2.10,1.80,2.10,1.76,2.01,1.80,2.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,EC,21/04/2025,15:00,Rochdale,Fylde,0,0,D,0,0,...,1.98,1.83,1.99,1.86,2.05,1.86,1.98,1.80,1.85,1.78
523,EC,21/04/2025,15:00,Solihull,Boston Utd,3,2,H,1,2,...,1.83,1.98,1.87,1.99,1.87,2.05,1.8,1.99,1.89,2.02
524,EC,21/04/2025,15:00,Sutton,Barnet,1,3,A,1,1,...,1.85,1.95,1.85,2.01,1.85,2.08,1.77,2.01,1.92,1.93
525,EC,21/04/2025,15:00,Wealdstone,Maidenhead,1,1,D,1,1,...,2.03,1.78,2.07,1.80,2.07,1.80,2.03,1.78,2.12,1.80
526,EC,21/04/2025,15:00,York,Oldham,1,1,D,1,0,...,1.80,2.00,1.85,2.00,1.94,2.01,1.85,1.93,1.81,2.02

# Multiples temporadas

In [96]:
for season in range(15,21):
    print(season)

15
16
17
18
19
20

In [86]:

#Crear lista de ligas

import pandas as pd

leagues = ['E0', 'E2', 'E3',]
frames = []

#Hacer loop rango de temporadas e insertar una nueva columna

for league in leagues:
    for season in range(15,21):
        df= pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv')
        df.insert(1,'season',season)
        frames.append(df)

In [88]:
#Total de frames (6 temporadas x 3 ligas
len(frames)

18

In [92]:
#Mostrar 1er y ultimo elemento (columna season fue creada
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

# Proyecto 1 Parte 3

### Organizar Data en un diccionario

In [142]:
# crear diccionario con nombre original de liga como llave
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [148]:
# Obtener un elemento del diccionario
dict_countries['Spanish La Liga']

'SP1'

In [152]:
# Loop sobre diccionario
for league in dict_countries:
    print(league)

for league in dict_countries:
    print(dict_countries [league])

Spanish La Liga
Spanish Segunda Division
German Bundesliga
English Premier League
English League 1
English League 2
SP1
SP2
D1
E0
E2
E3

In [159]:
#Crear lista de ligas
import pandas as pd

dict_historical_data = {}

#leagues = ['E0', 'E2', 'E3',]

#Hacer loop sobre llaves de diccionario

for league in dict_countries:
    frames = []
    for season in range(15,21):
        df= pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv')
        df.insert(1,'season',season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [165]:
#Mostrar dataframe dentro de dict_historical_data
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [167]:
#Mostrar dataframe dentro de dict_historical_data
dict_historical_data['Spanish Segunda Division']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP2,15,22/08/15,Alcorcon,Mallorca,2,0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP2,15,22/08/15,Cordoba,Valladolid,1,0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP2,15,22/08/15,Huesca,Alaves,2,3,A,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP2,15,22/08/15,Llagostera,Osasuna,0,2,A,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP2,15,23/08/15,Almeria,Leganes,3,2,H,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,SP2,20,30/05/2021,Mirandes,Sabadell,0,2,A,0.0,0.0,...,1.74,0.50,2.02,1.83,2.05,1.86,2.06,1.89,2.00,1.83
458,SP2,20,30/05/2021,Ponferradina,Mallorca,2,2,D,1.0,1.0,...,1.83,0.25,2.00,1.85,2.02,1.89,2.04,1.92,1.99,1.85
459,SP2,20,30/05/2021,Sp Gijon,Almeria,0,2,A,0.0,0.0,...,1.83,-0.75,1.80,2.05,1.84,2.08,1.89,2.08,1.83,2.02
460,SP2,20,30/05/2021,Vallecano,Lugo,0,1,A,0.0,1.0,...,1.87,-1.00,1.95,1.90,1.97,1.93,2.02,1.94,1.96,1.88
461,SP2,20,30/05/2021,Zaragoza,Leganes,0,5,A,0.0,3.0,...,1.64,0.50,1.83,2.02,1.85,2.07,1.87,2.08,1.80,2.04