In [75]:
# importar pandas
import pandas as pd

In [ ]:
# Opcional: usa el pd.set_option() para mostrar todas las filas de un dataframe por defecto

# Crear un DataFrame

In [76]:
# leer el archivo csv "bestsellers with categories" (data sobre los 50 libros más vendidos de Amazon de 2009 a 2019.)
Libros = pd.read_csv('bestsellers+with+categories.csv')

In [77]:
# acceder al atributo shape
Libros.shape

(550, 7)

In [78]:
# encontrar el tipo de data de cada columna
Libros.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
dtype: object

# Mostrar un DataFrame

In [79]:
# mostrar primeras 5 filas de un dataframe
print(Libros.head())

                                                Name  \
0                      10-Day Green Smoothie Cleanse
1                                  11/22/63: A Novel
2            12 Rules for Life: An Antidote to Chaos
3                             1984 (Signet Classics)
4  5,000 Awesome Facts (About Everything!) (Natio...

                     Author  User Rating  Reviews  Price  Year        Genre
0                  JJ Smith          4.7    17350      8  2016  Non Fiction
1              Stephen King          4.6     2052     22  2011      Fiction
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3             George Orwell          4.7    21424      6  2017      Fiction
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [83]:
# encontrar valores estadisticos de un dataframe (mean, std, min, max)
Libros['Price'].mean()
Libros['Price'].std()
Libros['Price'].min()
Libros['Price'].max()

105

# Agregar una nueva Columna

In [86]:
# Tu tarea es crear una columna llamada 'Critic Rating' que deberia tener numeros random enteros entre 1 y 4

# 1.importar numpy y crear 550 numeros random enteros entre 1 y 4
import numpy as np

numero_random = np.random.randint(1,5, size=550)

# 2.agregar nueva columna 'Critic Rating' al dataframe usando los numeros random creados
print(Libros)
Libros['Critic Rating'] = numero_random
# Obs: Los numeros aleatorios en la columna 'Critic Rating' seran diferentes entre tu solucion y la mia, pero vamos a concetrarnos en el codigo en esta seccion.

                                                  Name  \
0                        10-Day Green Smoothie Cleanse
1                                    11/22/63: A Novel
2              12 Rules for Life: An Antidote to Chaos
3                               1984 (Signet Classics)
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)
546  You Are a Badass: How to Stop Doubting Your Gr...
547  You Are a Badass: How to Stop Doubting Your Gr...
548  You Are a Badass: How to Stop Doubting Your Gr...
549  You Are a Badass: How to Stop Doubting Your Gr...

                       Author  User Rating  Reviews  Price  Year        Genre
0                    JJ Smith          4.7    17350      8  2016  Non Fiction
1                Stephen King          4.6     2052     22  2011      Fiction
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3               George Orwell          4.7    21424      6  2017      Fiction
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction
..                        ...          ...      ...    ...   ...          ...
545               Jeff Kinney          4.9     9413      8  2019      Fiction
546               Jen Sincero          4.7    14331      8  2016  Non Fiction
547               Jen Sincero          4.7    14331      8  2017  Non Fiction
548               Jen Sincero          4.7    14331      8  2018  Non Fiction
549               Jen Sincero          4.7    14331      8  2019  Non Fiction

[550 rows x 7 columns]

In [87]:
# mostrar 5 primeras filas
Libros.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4

# Atributos, Metodos y Funciones Basicas

In [88]:
# acceder al atributo "columns"
Libros.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre',
       'Critic Rating'],
      dtype='object')

# Seleccionar 2 o Mas Columnas de un Dataframe

In [90]:
# mover la columna 'Critic Rating' entre las columnas "User Rating" y "Reviews" Luego actualizar el dataframe
Libros[['Name','Author','User Rating','Critic Rating', 'Reviews', 'Price', 'Year', 'Genre']]

# Tip: Copiar y pegar los nombres de columna obtenidos con el atributo "columns" y reordenar los elementos usando [[]]

,Name,Author,User Rating,Critic Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,4,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,1,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,3,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,4,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,2,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,1,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,2,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,1,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,4,14331,8,2019,Non Fiction

In [91]:
# mostrar 5 primeras filas
Libros.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4

# Operaciones en Dataframes

In [93]:
# crear una columna llamada "Average Rating" usando la sigueinte formula: Average Rating = (User Rating + Critic Rating)/2
Libros['Average Rating'] = (Libros['User Rating'] + Libros['Critic Rating'])/2
print(Libros)

                                                  Name  \
0                        10-Day Green Smoothie Cleanse
1                                    11/22/63: A Novel
2              12 Rules for Life: An Antidote to Chaos
3                               1984 (Signet Classics)
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)
546  You Are a Badass: How to Stop Doubting Your Gr...
547  You Are a Badass: How to Stop Doubting Your Gr...
548  You Are a Badass: How to Stop Doubting Your Gr...
549  You Are a Badass: How to Stop Doubting Your Gr...

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction
1                Stephen King          4.6     2052     22  2011      Fiction
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3               George Orwell          4.7    21424      6  2017      Fiction
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction
..                        ...          ...      ...    ...   ...          ...
545               Jeff Kinney          4.9     9413      8  2019      Fiction
546               Jen Sincero          4.7    14331      8  2016  Non Fiction
547               Jen Sincero          4.7    14331      8  2017  Non Fiction
548               Jen Sincero          4.7    14331      8  2018  Non Fiction
549               Jen Sincero          4.7    14331      8  2019  Non Fiction

     Critic Rating  Average Rating
0                4            4.35
1                2            3.30
2                1            2.85
3                3            3.85
4                4            4.40
..             ...             ...
545              2            3.45
546              1            2.85
547              2            3.35
548              1            2.85
549              4            4.35

[550 rows x 9 columns]

In [94]:
# usar la funcion "round" para redondear los valores del dataframe a 1 decimal y actualizar el dataframe
Libros['Average Rating'].round(1)

0      4.4
1      3.3
2      2.8
3      3.8
4      4.4
      ...
545    3.4
546    2.8
547    3.4
548    2.8
549    4.4
Name: Average Rating, Length: 550, dtype: float64

# Contar Valores

In [95]:
# contar elementos en columna "Genre" por categoria y devolver la frecuencia relativa
Libros['Genre'].value_counts()

Genre
Non Fiction    310
Fiction        240
Name: count, dtype: int64

# Renombrar Columnas

In [101]:
# renombrar columnas "User Rating," "Critic Rating" y "Average Rating" a "UR," "CR" y "AR" Luego actualizar el dataframe con el parametro "inplace"
Libros.rename(columns={'User Rating': 'UR'},inplace=True)
Libros.rename(columns={'Critic Rating' : 'CR'}, inplace= True)
Libros.rename(columns={'Average Rating': 'AR'},inplace=True)

In [102]:
# mostrar 5 primeras filas
Libros.head()

,Name,Author,UR,Reviews,Price,Year,Genre,CR,AR
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4,4.35
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,2,3.30
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,1,2.85
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3,3.85
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4,4.40

In [103]:
# seleccionar solo columnas "Name", "Author", "UR", "CR", "AR" y "Year" y actualizar el dataframe

Libros[['Name', 'Author', 'UR', 'CR', 'AR', 'Year']]

,Name,Author,UR,CR,AR,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,4,4.35,2016
1,11/22/63: A Novel,Stephen King,4.6,2,3.30,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,1,2.85,2018
3,1984 (Signet Classics),George Orwell,4.7,3,3.85,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,4,4.40,2019
...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,2,3.45,2019
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,1,2.85,2016
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,2,3.35,2017
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,1,2.85,2018
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,4,4.35,2019

# Ordenar el dataframe

In [ ]:
# ordenar el dataframe en forma descendente segun las columnas "UR" y "CR"
Libros.sort_values(by = ['UR', 'CR'],ascending=False)

,Name,Author,UR,Reviews,Price,Year,Genre,CR,AR
85,Dog Man: Fetch-22: From the Creator of Captain...,Dav Pilkey,4.9,12619,8,2019,Fiction,4,4.45
151,Hamilton: The Revolution,Lin-Manuel Miranda,4.9,5867,54,2016,Non Fiction,4,4.45
153,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,4.9,19622,30,2016,Fiction,4,4.45
155,Harry Potter and the Goblet of Fire: The Illus...,J. K. Rowling,4.9,7758,18,2019,Fiction,4,4.45
157,Harry Potter and the Sorcerer's Stone: The Ill...,J.K. Rowling,4.9,10052,22,2016,Fiction,4,4.45
...,...,...,...,...,...,...,...,...,...
22,Allegiant,Veronica Roth,3.9,6310,13,2013,Fiction,1,2.45
106,Fifty Shades of Grey: Book One of the Fifty Sh...,E L James,3.8,47265,14,2012,Fiction,2,2.90
107,Fifty Shades of Grey: Book One of the Fifty Sh...,E L James,3.8,47265,14,2013,Fiction,2,2.90
132,Go Set a Watchman: A Novel,Harper Lee,3.6,14982,19,2015,Fiction,2,2.80
353,The Casual Vacancy,J.K. Rowling,3.3,9372,12,2012,Fiction,3,3.15